name: Production mode

on:
  schedule:
    - cron: '18 */2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prodmode:
    runs-on: ubuntu-latest
    steps:
    - name: Check no debug mode
      run: |
        composer create-project --no-dev spaze/url-checker url-checker
        php url-checker/bin/check.php https://www.michalspacek.cz 200 "Michal Špaček" "Tracy Debug"
